# Generated by Django 4.2.5 on 2023-10-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qte',
            field=models.IntegerField(verbose_name='Quantity product'),
        ),
    ]
